# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.12-slim

# ------------------------------------------

FROM ghcr.io/astral-sh/uv:0.6.13 AS uv

# ------------------------------------------

FROM python:${PYTHON_VERSION} AS builder

ARG SERVICE_NAME 
ARG MODULE_NAME

COPY --from=uv /uv /usr/local/bin/uv

WORKDIR /app

COPY uv.lock pyproject.toml ./
COPY libs/ ./libs/
COPY services/${MODULE_NAME}/ ./services/${MODULE_NAME}/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync \
    --frozen \
    --no-dev \
    --no-default-groups \
    --package ${SERVICE_NAME} \
    --extra train
# ------------------------------------------

FROM python:${PYTHON_VERSION} AS runner

ARG MODULE_NAME
ENV MODULE_NAME=${MODULE_NAME}

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY --from=uv /uv /usr/local/bin/uv
COPY --from=builder /app ./

ENTRYPOINT ["sh", "-c", ".venv/bin/python services/${MODULE_NAME}/src/${MODULE_NAME}/train_pipeline.py --buildNum $BUILD_NUM"]