[project]
name = "doc-verify"
version = "0.1.0"
description = "Document Verification Service for ID"
requires-python = ">=3.12"

dependencies = [
    "ml-common",
    "openocr-python>=0.0.10",
    "onnxruntime>=1.24.1",
    "fastapi>=0.117.1",
    "uvicorn>=0.37.0",
]

[project.optional-dependencies]
train = [
    "torch>=2.0.0",
    "torchvision>=0.23.0",
    "torchaudio>=2.8.0",
    "transformers>=4.56.0",
    "accelerate>=1.10.1",
    "datasets>=4.0.0",
    "matplotlib>=3.10.1",
]

gui = [
  "ultralytics>=8.3.192",
]

ci = [
  "ultralytics-opencv-headless>=8.3.192"
]

cpu = [
  "torch>=2.9.1",
  "torchvision>=0.24.1",
]

cu128 = [
  "torch>=2.9.1",
  "torchvision>=0.24.1",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true